# Generated by Django 2.2.4 on 2019-09-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HLS', 'Heels'), ('SNKS', 'Sneakers'), ('BTS', 'Boots'), ('O', 'Official'), ('C&S', 'Crocs & Sandals'), ('SPRT', 'Sports'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
